export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';
export const RESET_ERROR_MESSAGE="RESET_ERROR_MESSAGE";

export const LOAD_COURSES_SUCCESS = 'LOAD_COURSES_SUCCESS';
export const LOAD_AUTHORS_SUCCESS = 'LOAD_AUTHORS_SUCCESS';
export const CREATE_COURSE_SUCCESS = 'CREATE_COURSE_SUCCESS';
export const UPDATE_COURSE_SUCCESS = 'UPDATE_COURSE_SUCCESS';

export const AUTHENTICATION_SUCCESS = 'AUTHENTICATION_SUCCESS';
export const AUTHENTICATION_FAILURE = 'AUTHENTICATION_FAILURE';

export const CREATE_APARTMENT_SUCCESS = 'CREATE_APARTMENT_SUCCESS';
export const CREATE_APARTMENT_FAILURE = "CREATE_APARTMENT_FAILURE";
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const OTP_SUCCESS = 'OTP_SUCCESS';
export const OTP_FAILURE = 'OTP_FAILURE';
export const GET_ADDRESS_SUCCESS = 'GET_ADDRESS_SUCCESS';
export const GET_ADDRESS_FAILURE = 'GET_ADDRESS_FAILURE';

export const GET_MEMBERS_SUCCESS = 'GET_MEMBERS_SUCCESS';
export const GET_MEMBERS_FAILURE = 'GET_MEMBERS_FAILURE';
export const ADD_MEMBER_SUCCESS = 'ADD_MEMBER_SUCCESS';
export const ADD_MEMBER_FAILURE = 'ADD_MEMBER_FAILURE';
export const EDIT_MEMBER_SUCCESS = 'EDIT_MEMBER_SUCCESS';
export const EDIT_MEMBER_FAILURE = 'EDIT_MEMBER_FAILURE';
export const DELETE_MEMBER_SUCCESS = 'DELETE_MEMBER_SUCCESS';
export const DELETE_MEMBER_FAILURE = 'DELETE_MEMBER_FAILURE';

export const GET_REQUESTS_SUCCESS = 'GET_REQUESTS_SUCCESS';
export const GET_REQUESTS_FAILURE = 'GET_REQUESTS_FAILURE';
export const UPDATE_REQUEST_SUCCESS = 'UPDATE_REQUEST_SUCCESS';
export const UPDATE_REQUEST_FAILURE = 'UPDATE_REQUEST_FAILURE';


export const GET_VENDORS_SUCCESS = 'GET_VENDORS_SUCCESS';
export const GET_VENDORS_FAILURE = 'GET_VENDORS_FAILURE';
export const ADD_VENDOR_SUCCESS = 'ADD_VENDOR_SUCCESS';
export const ADD_VENDOR_FAILURE = 'ADD_VENDOR_FAILURE';
export const EDIT_VENDOR_SUCCESS = 'EDIT_VENDOR_SUCCESS';
export const EDIT_VENDOR_FAILURE = 'EDIT_VENDOR_FAILURE';
export const DELETE_VENDOR_SUCCESS = 'DELETE_VENDOR_SUCCESS';
export const DELETE_VENDOR_FAILURE = 'DELETE_VENDOR_FAILURE';
export const LIKE_VENDOR_SUCCESS = 'LIKE_VENDOR_SUCCESS';
export const LIKE_VENDOR_FAILURE = 'LIKE_VENDOR_FAILURE';
export const DISLIKE_VENDOR_SUCCESS = 'DISLIKE_VENDOR_SUCCESS';
export const DISLIKE_VENDOR_FAILURE = 'DISLIKE_VENDOR_FAILURE';



export const CREATE_MAINTAINENCE_SUCCESS = 'CREATE_MAINTAINENCE_SUCCESS';
export const CREATE_MAINTAINENCE_FAILURE = 'CREATE_MAINTAINENCE_FAILURE';
export const PAY_MAINTAINENCE_SUCCESS = 'PAY_MAINTAINENCE_SUCCESS';
export const PAY_MAINTAINENCE_FAILURE = 'PAY_MAINTAINENCE_FAILURE';
export const BLOCK_MAINTAINENCE_SUCCESS="BLOCK_MAINTAINENCE_SUCCESS";
export const BLOCK_MAINTAINENCE_FAILURE="BLOCK_MAINTAINENCE_FAILURE";
export const ADD_EXPENSE_SUCCESS = 'ADD_EXPENSE_SUCCESS';
export const ADD_EXPENSE_FAILURE = 'ADD_EXPENSE_FAILURE';
export const GET_MEMBER_STMT_SUCCESS = 'GET_MEMBER_STMT_SUCCESS';
export const GET_MEMBER_STMT_FAILURE = 'GET_MEMBER_STMT_FAILURE';
export const GET_SOCIETY_FUNDS_SUCCESS = 'GET_SOCIETY_FUNDS_SUCCESS';
export const GET_SOCIETY_FUNDS_FAILURE = 'GET_SOCIETY_FUNDS_FAILURE';
export const GET_MAINTAINENCE_DETAILS_SUCCESS = 'GET_MAINTAINENCE_DETAILS_SUCCESS';
export const GET_MAINTAINENCE_DETAILS_FAILURE = 'GET_MAINTAINENCE_DETAILS_FAILURE';
export const GET_ALL_MAINTAINENCE_SUCCESS = 'GET_ALL_MAINTAINENCE_SUCCESS';
export const GET_ALL_MAINTAINENCE_FAILURE = 'GET_ALL_MAINTAINENCE_FAILURE';
export const GET_PENDING_MAINTAINENCE_SUCCESS = 'GET_PENDING_MAINTAINENCE_SUCCESS';
export const GET_PENDING_MAINTAINENCE_FAILURE = 'GET_PENDING_MAINTAINENCE_FAILURE';


export const ADD_DISCUSSION_SUCCESS = 'ADD_DISCUSSION_SUCCESS';
export const ADD_DISCUSSION_FAILURE = 'ADD_DISCUSSION_FAILURE';
export const EDIT_NOTICE_SUCCESS = 'EDIT_NOTICE_SUCCESS';
export const EDIT_NOTICE_FAILURE = 'EDIT_NOTICE_FAILURE';
export const ADD_MESSAGE_SUCCESS = 'ADD_MESSAGE_SUCCESS';
export const ADD_MESSAGE_FAILURE = 'ADD_MESSAGE_FAILURE';
export const DELETE_MESSAGE_SUCCESS = 'DELETE_MESSAGE_SUCCESS';
export const DELETE_MESSAGE_FAILURE = 'DELETE_MESSAGE_FAILURE';
export const CLOSE_DISCUSSION_SUCCESS = 'CLOSE_DISCUSSION_SUCCESS';
export const CLOSE_DISCUSSION_FAILURE = 'CLOSE_DISCUSSION_FAILURE';
export const GET_NOTICES_SUCCESS = 'GET_NOTICES_SUCCESS';
export const GET_NOTICES_FAILURE = 'GET_NOTICES_FAILURE';
export const GET_COMPLAINTS_SUCCESS = 'GET_COMPLAINTS_SUCCESS';
export const GET_COMPLAINTS_FAILURE = 'GET_COMPLAINTS_FAILURE';
export const GET_DISCUSSIONS_SUCCESS = 'GET_DISCUSSIONS_SUCCESS';
export const GET_DISCUSSIONS_FAILURE = 'GET_DISCUSSIONS_FAILURE';

export const GET_CLASSES_SUCCESS = 'GET_CLASSES_SUCCESS';
export const GET_CLASSES_FAILURE = 'GET_CLASSES_FAILURE';

export const GET_STUDENT_CLASSES_SUCCESS ='GET_STUDENT_CLASSES_SUCCESS';
export const ADD_CLASSES_SUCCESS = 'ADD_CLASSES_SUCCESS';
export const ADD_CLASSES_FAILURE = 'ADD_CLASSES_FAILURE';
export const BOOK_CLASSES_SUCCESS = 'BOOK_CLASSES_SUCCESS';
export const BOOK_CLASSES_FAILURE = 'BOOK_CLASSES_FAILURE';

export const ADD_TEACHER_EMAIL = 'ADD_TEACHER_EMAIL';
export const ADD_STUDENT_DATA ='ADD_STUDENT_DATA';

