export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';
export const RESET_ERROR_MESSAGE="RESET_ERROR_MESSAGE";



export const AUTHENTICATION_SUCCESS = 'AUTHENTICATION_SUCCESS';
export const AUTHENTICATION_FAILURE = 'AUTHENTICATION_FAILURE';


export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const OTP_SUCCESS = 'OTP_SUCCESS';
export const OTP_FAILURE = 'OTP_FAILURE';

export const GET_CLASSES_SUCCESS = 'GET_CLASSES_SUCCESS';
export const GET_CLASSES_FAILURE = 'GET_CLASSES_FAILURE';

export const GET_STUDENT_CLASSES_SUCCESS ='GET_STUDENT_CLASSES_SUCCESS';
export const ADD_CLASSES_SUCCESS = 'ADD_CLASSES_SUCCESS';
export const ADD_CLASSES_FAILURE = 'ADD_CLASSES_FAILURE';
export const BOOK_CLASSES_SUCCESS = 'BOOK_CLASSES_SUCCESS';
export const BOOK_CLASSES_FAILURE = 'BOOK_CLASSES_FAILURE';

export const ADD_TEACHER_EMAIL = 'ADD_TEACHER_EMAIL';
export const ADD_STUDENT_DATA ='ADD_STUDENT_DATA';

