import './assets/vendor/jquery.easing/jquery.easing.min.js';
import './assets/vendor/php-email-form/validate.js';
import './assets/vendor/counterup/counterup.min.js';
import './assets/vendor/isotope-layout/isotope.pkgd.min.js';
import './assets/vendor/venobox/venobox.min.js';
import './assets/vendor/bootstrap/css/bootstrap.min.css';
import './assets/vendor/icofont/icofont.min.css';
// import '../../Bethany/assets/vendor/boxicons/css/boxicons.min.css';
// import '../../Bethany/assets/vendor/remixicon/remixicon.css';
import './assets/vendor/venobox/venobox.css';
import './assets/vendor/owl.carousel/assets/owl.carousel.min.css';
import './assets/vendor/aos/aos.css';
import './assets/css/style.css';
import './assets/js/main.js';
