export const blogs = [{
  id: 1,
  topic: "How To Learn Data Science If You’re Broke",
  author: "Harrison Jansma",
  readtime: 9,
  date: "Sep 16, 2018",
  initialContent: "Over the last year, I taught myself data science. I learned from hundreds of online",
  totalReads: "21",
  img: "https://cdn-images-1.medium.com/fit/t/1600/480/0*zV1Hxq8zOqi7oEQS",
  category: "DataScience",
  subcategory: "Data Science",
  keywords: "Data Science,Machine Learning,Artificial Intelligence",
  uniqueid: "how-to-learn-data-science-if-youre-broke-7ecc408b53c7"
},
{
  id: 2,
  topic: "The best Mario Kart character according to data science",
  author: "Civis Analytics",
  readtime: 6,
  date: "Jun 8, 2018",
  initialContent: "Mario Kart was a staple of my childhood — my friends and I would spend hours after school as Mario, Luigi, and other characters",
  totalReads: "54",
  img: "https://cdn-images-1.medium.com/fit/t/1600/480/0*pfZQeBhhY9U4CSyJ",
  category: "Data Science",
  subcategory: "Data Science",
  keywords: "Data Science,Machine Learning,Artificial Intelligence",
  uniqueid: "the-best-mario-kart-character-according-to-data-science-7dfb65d4"
},
{
  id: 3,
  topic: "If you want to learn Data Science, start with one of these programming classes",
  author: "David Venturi",
  readtime: 14,
  date: "Jul 9, 2018",
  initialContent: "A year ago, I was a numbers geek with no coding background. After trying an online programming course,A year ago, I was a numbers geek with no coding background. After trying an online programming course,",
  totalReads: 212,
  img: "https://cdn-images-1.medium.com/fit/t/1600/480/1*EMTsMs0U6QcJ0bJOfoJ5_Q.jpeg",
  category: "Data Science",
  subcategory: "Data Science",
  keywords: "Data Science,Machine Learning,Artificial Intelligence",
  uniqueid: "if-you-want-to-learn-data-science-start-with-one-of-these-progra"
},
{
  id: 4,
  topic: "Essential Math for Data Science",
  author: "Tirthajyoti Sarkar ",
  readtime: 8,
  date: "Jul 9, 2018",
  initialContent: "The key topics to master to become a better data scientist  ",
  totalReads: 212,
  img: "https://cdn-images-1.medium.com/focal/1600/480/54/42/1*lHY-KWrS51N5Gn5pLmXPCA.jpeg",
  category: "Data Science",
  subcategory: "Data Science",
  keywords: "Data Science,Machine Learning,Artificial Intelligence",
  uniqueid: "essential-math-for-data-science-why-and-how-e88271367fbd"
},{
  id: 5,
  topic: "I ranked every Intro to Data Science course on the internet, based on thousands of data pointsI ranked every Intro to Data Science course on the internet, based on thousands of data points",
  author: "David Venturi",
  readtime: 13,
  date: "Jul 9, 2018",
  initialContent: "A year ago, I dropped out of one of the best computer science programs",
  totalReads: 212,
  img: "https://cdn-images-1.medium.com/fit/t/1600/480/1*s4RqFZgSAluZq2lcWhp5JA.png",
  category: "Data Science",
  subcategory: "Data Science",
  keywords: "Data Science,Machine Learning,Artificial Intelligence",
  uniqueid: "i-ranked-all-the-best-data-science-intro-courses-based-on-thousa"
},
{
  id: 6,
  topic: "The best Data Science courses on the internet, ranked by your reviews",
  author: "David Venturi",
  readtime: 12,
  date: "Apr 20, 2016",
  initialContent: "A year and a half ago, I dropped out of one of the best computer science programs",
  totalReads: 212,
  img: "https://cdn-images-1.medium.com/fit/t/1600/480/1*_XW9Jb0dJeQkJRDe7cz0lw.jpeg",
  category: "Data Science",
  subcategory: "Data Science",
  keywords: "Data Science,Machine Learning,Artificial Intelligence",
  uniqueid: "the-best-data-science-courses-on-the-internet-ranked-by-your-rev"
},
{
  id: 7,
  topic: "Bringing the best out of Jupyter Notebooks for Data Science",
  author: "Parul Pandey",
  readtime: 9,
  date: "Apr 20, 2016",
  initialContent: "Enhance Jupyter Notebook’s productivity",
  totalReads: 212,
  img: "https://cdn-images-1.medium.com/fit/t/1600/480/0*kFimvWp5vJtxn4ws",
  category: "Data Science",
  subcategory: "Data Science",
  keywords: "Data Science,Machine Learning,Artificial Intelligence",
  uniqueid: "bringing-the-best-out-of-jupyter-notebooks-for-data-science-f087"
},
{
  id: 8,
  topic: "Python for Data Science: 8 Concepts You May Have Forgotten",
  author: "Conor Dewey",
  readtime: 7,
  date: "Apr 20, 2016",
  initialContent: "Mastering the little things in Python",
  totalReads: 212,
  img: "https://cdn-images-1.medium.com/fit/t/1600/480/1*LzTFHgvCbuuQvMS2RRE_Cg.png",
  category: "Data Science",
  subcategory: "Data Science",
  keywords: "Data Science,Machine Learning,Artificial Intelligence",
  uniqueid: "python-for-data-science-8-concepts-you-may-have-forgotten-i-did-"
},
{
  id: 9,
  topic: "I Dropped Out of School to Create My Own Data Science Master’s — Here’s My Curriculum",
  author: "David Venturi",
  readtime: 6,
  date: "Nov 3, 2019",
  initialContent: "I dropped out of a top computer science program to teach myself data science using online resources",
  totalReads: 212,
  img: "https://cdn-images-1.medium.com/fit/t/1600/480/1*uQrLhsTuvnC3fpQI4S3B7w.png",
  category: "Data Science",
  subcategory: "Data Science",
  keywords: "Data Science,Machine Learning,Artificial Intelligence",
  uniqueid: "i-dropped-out-of-school-to-create-my-own-data-science-master-s-h"
},
{
  id: 10,
  topic: "Want a data science job? Use the weekend project principle to get it",
  author: "Daniel Bourke",
  readtime: 4,
  date: "Nov 2, 2018",
  initialContent: "Online course certificates are",
  totalReads: 212,
  img: "https://cdn-images-1.medium.com/fit/t/1600/480/1*ousJEOOp5wDC1T6tFnAOCA.jpeg",
  category: "Data Science",
  subcategory: "Data Science",
  keywords: "Data Science,Machine Learning,Artificial Intelligence",
  uniqueid: "want-a-data-science-job-use-the-weekend-project-principle-to-get"
},
{
  id: 11,
  topic: "Why you shouldn’t be a data science generalist",
  author: "Jeremie Harris",
  readtime: 6,
  date: "Apr 30, 2018",
  initialContent: "I work at a data science mentorship startup, and I’ve found there’s a single",
  totalReads: 212,
  img: "https://cdn-images-1.medium.com/fit/t/1600/480/0*3BuE4ZAwFjxeiBTW.jpg",
  category: "Data Science",
  subcategory: "Data Science",
  keywords: "Data Science,Machine Learning,Artificial Intelligence",
  uniqueid: "why-you-shouldnt-be-a-data-science-generalist-f69ea37cdd2c"
},{
  id: 12,
  topic: "Data Science for Startups: Introduction",
  author: "Ben Weber",
  readtime: 4,
  date: "Aug 23, 2018",
  initialContent: "I recently changed industries and joined a startup company where I’m responsible forI recently changed industries and joined a startup company where I’m responsible for",
  totalReads: 212,
  img: "https://cdn-images-1.medium.com/max/720/1*z0AJeiYe_9qltVgp2g7zkw.jpeg",
  category: "Data Science",
  subcategory: "Data Science",
  keywords: "Data Science,Machine Learning,Artificial Intelligence",
  uniqueid: "data-science-for-startups-introduction-80d022a18aec"
}];
